META_ARC: "siamfcos_r50_dwxcorr_train"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [3]
    PRETRAINED: '../pretrained_models/resnet50.model'
    TRAIN_LAYERS: ['layer2', 'layer3']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.1

ADJUST:
    ADJUST: true
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [1024]
        out_channels: [256]

FCOS:
    TYPE: 'DepthwiseFCOS'
    KWARGS:
        in_channels: 256
        out_channels: 256
    IOU_LOSS_TYPE: 'iou'
    FOCAL_LOSS_GAMMA: 2.0
    FOCAL_LOSS_ALPHA: 0.25

MASK:
    MASK: False

ANCHOR:
    STRIDE: 8
    RATIOS: [1]
    SCALES: [8]
    ANCHOR_NUM: 1

TRACK:
    TYPE: 'SiamFCOSTracker'
    PENALTY_K: 0.04
    WINDOW_INFLUENCE: 0.44
    LR: 0.33
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8
    CONTEXT_AMOUNT: 0.5

TRAIN:
    EPOCH: 20
    START_EPOCH: 0
    BATCH_SIZE: 48
    BASE_LR: 0.005
    CLS_WEIGHT: 1.0
    CEN_WEIGHT: 1.2
    LOC_WEIGHT: 1.2
    RESUME: ''

    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.0005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.001
            end_lr: 0.005
            step: 1

DATASET:
    NAMES:
    - 'VID'
    - 'COCO'
    - 'DET'
# - 'YOUTUBEBB'
    TEMPLATE:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.0
    GRAY: 0.0
